### PR TITLE
Fixes #3505 - Remove animations/scrolling for prefers-reduced-motion

### LINKED ISSUE #3505: [A11Y] Bug report form can trigger migraines and motion sickness for users with visual or vestibular issues
Visiting https://webcompat.com/issues/new

1. Type url into 1st field.

2. Click confirm.

3. Get hit with blinding pain. Get migraine and motion sickness. It's hard to see as it happens, but I think there's flashing and smooth scrolling. Flashing often gives me migraines, and smooth scrolling, zooming, etc. always reliably do.

See also https://github.com/webcompat/webcompat.com/issues/3134

### PR DESCRIPTION
**Pull request by ksy36**
Fixes https://github.com/webcompat/webcompat.com/issues/3505 (and https://github.com/webcompat/webcompat.com/issues/3735)

### CODE REVIEW

File: webcompat/static/js/lib/wizard/helpers/postMessageParser.js [hunk 1]
```diff
@@ -20,9 +18,6 @@ const handleMessage = (message) => {
 
   sendAnalyticsCS(utm_campaign, utm_source);
   if (url) {
-    showStep("category", {
-      url: extractPrettyUrl(url),
-    });
     updateUrl(url);
```
Comment (ksy36) [inline webcompat/static/js/lib/wizard/helpers/postMessageParser.js:21]: I've also removed the "skip the url and scroll to the category step" when reporting through "Report site issue". It was part of the experiment to try and improve the form drop off. Thinking it might be confusing for new users as it happens immediately, skipping the part that we're looking for web compatibility issues (and "Learn more about web compatibility" pop up) .

File: webcompat/templates/issue/thanks.jst [hunk 2]
```diff
@@ -8,4 +8,3 @@
   <p>You can return to this web page at any time to track the progress of this report.</p>
 </section>
 </script>
-˚
```
Comment (denschub) [inline webcompat/templates/issue/thanks.jst:11]: 😆

File: webcompat/static/js/lib/wizard/ui-utils.js [hunk 3]
```diff
@@ -52,8 +69,19 @@ export const showContainer = (container, cb) => {
...
+  domElement.style.display = "none";
+  container.removeClass("open");
+};
+
 export const hideContainer = (container) => {
   const domElement = container[0];
+
+  if (isReducedMotion()) {
+    return hideContainerReduced(container);
+  }
```
Comment (denschub) [inline webcompat/static/js/lib/wizard/ui-utils.js:83]: Is there a reason to have a second hide-method instead of setting the `duration` in the animation-call below to 0? Intuitively, it feels like it would be simpler to do that, but my intuition might be wrong.

Comment (ksy36) [reply webcompat/static/js/lib/wizard/ui-utils.js:83]: I've tried it yeah, but the function inside `anime.begin` callback doesn't run with duration: 0 :(
```js
    begin: () => {
      domElement.style.display = "flex";
    },
```
(this is basically what's making next step visible).

Tried to increase duration to 20 or 40, then it works most of the time and sometime doesn't, which seemed pretty fragile, so I just decided to have a separate function to have more control.

File: webcompat/templates/issue/thanks.jst (hunk 2 above)
Comment (ksy36) [reply webcompat/templates/issue/thanks.jst:11]: 🙈

File: webcompat/static/js/lib/wizard/ui-utils.js (hunk 3 above)
Comment (denschub) [reply webcompat/static/js/lib/wizard/ui-utils.js:83]: Ah, that's a shame. Thanks for explaining!

**Review by denschub — APPROVED** [review]
Thanks for working on this!

**Comment by ksy36** [comment]
Thank you!
