### PR TITLE
Fixes #3396 - Add ability to navigate and select categories via keyboard

### LINKED ISSUE #3396: [A11Y] Unable to select issue category/browser icon/screenshot upload using “Tab” key
**Browser / Version**: Firefox Nightly 80.0a1 (2020-07-15)
**Operating System**: Windows 10 Pro

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/issues/new
2. Using "Tab" key, navigate to the URL field and fill it in. 
3. Using "Tab" key, navigate to "Confirm" button.
4. Using "Enter" key, activate "Confirm" button and move to the next section.
5. Using "Tab" key, try to select a category.
6. Observe behavior.

**Expected Behavior:**
Category is active and can be selected.

**Actual Behavior:**
Category can't be selected.

**Notes:**
1. Screenshot attached.
2. The issue is also reproducible for browser selection and screenshot selection.
3. Taking this in consideration a report can't be submitted using keyboard keys.
download
4. According to "Inspector>Accessibility" tab, the elements "must be focusable and should have interactive semantics".
image

Watchers:
@softvision-oana-arbuzov
@cipriansv

### PR DESCRIPTION
**Pull request by miketaylr**
r? @ksy36

### CODE REVIEW

**Comment by miketaylr** [comment]
OK, r? @ksy36

File: webcompat/static/js/lib/wizard/steps/sub-category.js [hunk 1]
```diff
@@ -36,7 +40,12 @@ const handleSubCategory = (event) => {
   notify.publish("showStep", { id: "confirmBrowser" });
 };
 
-radio.on("change", handleSubCategory);
+const initListeners = () => {
+  radio.on("change", handleSubCategory);
+  addKeyDownListeners(".step-subproblem");
```
Comment (ksy36) [inline webcompat/static/js/lib/wizard/steps/sub-category.js:45]: this is rather a nitpick, but perhaps you could pass `container` variable to addKeyDownListeners (since we already query dom for it at the top of each file), and then inside the function query for labels within that container. I'll leave this up to you though :)

Comment (miketaylr) [reply webcompat/static/js/lib/wizard/steps/sub-category.js:45]: Ah! Yeah, that's a bit cleaner. Let me make the change. thxxx
