### PR TITLE
Fixes #2188. Handle legacy details param data.

### LINKED ISSUE #2188: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
STR:

In 59 or below, click "Report Site Issue" from the page actions menu.

Expected: Get a screenshot
Actual: Don't, and have this error in the console.

I think I did this. 😿

### PR DESCRIPTION
**Pull request by miketaylr**
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1441325.

🙈 

r? @zoepage 
r? @karlcow

### CODE REVIEW

File: webcompat/static/js/lib/bugform.js [hunk 1]
```diff
@@ -544,7 +554,10 @@ function BugForm() {
         if (response && response.status === 413) {
           msg =
             "The image is too big! Please choose something smaller than 4MB.";
-          wcEvents.trigger("flash:error", { message: msg, timeout: 5000 });
+          wcEvents.trigger("flash:error", {
```
Comment (miketaylr) [inline webcompat/static/js/lib/bugform.js]: I'm not sure why prettier wanted this to change, but looks better now!

**Comment by zoepage** [comment]
LGTM!

**Comment by miketaylr** [comment]
Thanks @karlcow and @zoepage.
