### PR TITLE
fix #1135 update functional tests for cross browser testing

### LINKED ISSUE #1135: update functional tests for cross-browser testing
this is broken out from #980 for running functional tests on browserstack (firefox and chrome). this is part 1/3, updating a few tests that would break on one browser but not the other.

* search-auth.js (add 'Search works by Return key' to cover another common use case, slightly update name of existing test to 'Search works by icon click')
* index-non-auth.js ('reporter addon link is shown': removed specific browser name from 'Download our * extension' search string)
* search-non-auth.js ('Clicking on label search suggestion works' currently failing local test) 
  * workaround: remove existing test but create new issue with test revision requirements:
  * (miketaylr) I think this is probably just a crappy test -- it assumes that there will be a bug with an android label on the /issues page. We should probably re-write it to just click on whatever label it finds, make a reference to its text, and then assert that we ended up with search results that match. I'd be OK with removing this test in a commit, as long as we file a bug to write a better test.
  * context of notes from [doc with current browserstack exceptions and comparisons to travis failures and local test results](https://docs.google.com/document/d/1h0XG-X0zT3AEiX6LtQFC7_AnQI2NP1TTTgOhS3zflOw/edit#heading=h.8kvmfxnp7g42)
* helpers.js (add timeout to login helper for time to add github authcode for local tests). ???is this necessary b/c no one else seems to have this issue?

### PR DESCRIPTION
**Pull request by cch5ng**
tests updated for cross browser testing

timeouts were added for a few tests that were failing locally (issues slow to load)

not sure if the timeout for login helper (github authcode) is necessary but otherwise I couldn't enter it in time...

* the removed android label test needs to be added in a new issue

r? @miketaylr

### CODE REVIEW

**Comment by cch5ng** [comment]
in https://github.com/webcompat/webcompat.com/pull/1137/commits/7ef82e25dac457bc5da8d02b807eadde9065d632

added a couple timeouts to resolve couple local failing tests reporting non auth

File: tests/functional/lib/helpers.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ define([
       .findByCssSelector('input[type=submit]').submit()
       .end()
       .findByCssSelector('button').submit()
+      .sleep(10000)
```
Comment (miketaylr) [inline tests/functional/lib/helpers.js]: Can we add a comment here explaining what the long wait is for?

**Comment by miketaylr** [comment]
(ugh seems like Travis is in some kind of weird state again: `5/67 tests failed` all unrelated to this changeset)

**Comment by miketaylr** [comment]
> not sure if the timeout for login helper (github authcode) is necessary but otherwise I couldn't enter it in time...

Let's merge it, but it should be possible to create some kind of param that people can pass into the config like `LOGIN_TIMEOUT=10` (that defaults to 0`. That can be a follow-up bug tho.

LGTM. If you can add that one comment feel free to merge.

**Comment by cch5ng** [comment]
> cch5ng: not sure if the timeout for login helper (github authcode) is necessary but otherwise I couldn't enter it in time...

> miketaylr: Let's merge it, but it should be possible to create some kind of param that people can pass into the config like LOGIN_TIMEOUT=10 (that defaults to 0`. That can be a follow-up bug tho.

> LGTM. If you can add that one comment feel free to merge.

done in https://github.com/webcompat/webcompat.com/pull/1137/commits/658a9bfefee79c1cdf29de800a416f6833bc8bcd

**Comment by cch5ng** [comment]
> (ugh seems like Travis is in some kind of weird state again: 5/67 tests failed all unrelated to this changeset)

yes, this is my short list of the travis failures. I checked whether they overlapped with the browserstack exceptions and two are in the same .js file but the css selectors that were not found were a little different. I saw something in the open issues about NSFW images and thought perhaps that was a fix for the travis tests.

FAIL: main - Comments (auth) - Empty vs non-empty comment button text (open issue) (10650ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cca00f9d-c852-4714-96b5-bdea4c8845dd/element / {"using":"css selector","value":".js-Issue-comment:nth-of-type(3)"}] Unable to locate element: {"method":"css selector","selector":".js-Issue-comment:nth-of-type(3)"}

FAIL: main - Comments (auth) - Empty vs non-empty comment button text (closed issue) (10570ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cca00f9d-c852-4714-96b5-bdea4c8845dd/element / {"using":"css selector","value":".js-Issue-comment:nth-of-type(3)"}] Unable to locate element: {"method":"css selector","selector":".js-Issue-comment:nth-of-type(3)"}

FAIL: main - Issues - Issue comments load (11605ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cca00f9d-c852-4714-96b5-bdea4c8845dd/element / {"using":"css selector","value":".js-Issue-comment"}] Unable to locate element: {"method":"css selector","selector":".js-Issue-comment"}

<tests/functional/issues-non-auth.js:46:10>

FAIL: main - Issues - NSFW images are blurred (11553ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cca00f9d-c852-4714-96b5-bdea4c8845dd/element / {"using":"css selector","value":".js-Issue-commentList .js-Comment-content p"}] Unable to locate element: {"method":"css selector","selector":".js-Issue-commentList .js-Comment-content p"}

<tests/functional/issues-non-auth.js:161:10>

FAIL: main - Issues - Clicking NSFW images toggles between blurry and not-blurry (11580ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cca00f9d-c852-4714-96b5-bdea4c8845dd/element / {"using":"css selector","value":".js-Issue-commentList .js-Comment-content p"}] Unable to locate element: {"method":"css selector","selector":".js-Issue-commentList .js-Comment-content p"}

<tests/functional/issues-non-auth.js:173:10>

**Comment by miketaylr** [comment]
I think I just wrote crappy tests that are time-dependent. There's gotta be a better way...
