### PR TITLE
Fixes #3049 - Clear the image preview when hitting an error

### LINKED ISSUE #3049: Unsupported format error message should be displayed above the “Upload screenshot”
URL: https://staging.webcompat.com/issues/new 
Browser / Version: Firefox Nightly 71.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/issues/new
    2. Fill in the requires information until reaching “Upload screenshot” area.
    3. Drag and drop a valid image type on the “Upload screenshot” area (e.g jpg.)
    4. Drag and drop an invalid type of file over the valid image (e.g txt).
    5. Observe behavior.
       
**Expected Behavior:**
Error message is displayed above the “Upload screenshot” area.

**Actual Behavior:**
An error message is displayed on the valid image and it is hardly visible.

**Note**
    1. Screenshot attached.
    2. Also reproducible on Chrome 78.0.3904.70
	
Affected area:
```html
<small class="label-icon-message form-upload-error">Image must be one of the following: jpe, jpg, jpeg, png, gif, or bmp.</small>
```

image

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

sv;

### PR DESCRIPTION
**Pull request by miketaylr**
Need to write some tests first. 

edit: Done.

### CODE REVIEW

File: webcompat/static/js/lib/issue-wizard-bugform.js [hunk 1]
```diff
@@ -1125,13 +1123,18 @@ BugForm.prototype.changeUploadText = function(textId) {
...
   Remove the upload image preview and hide the banner.
 */
-BugForm.prototype.removeUploadPreview = function(e) {
-  e.preventDefault();
+BugForm.prototype.removeUploadPreview = function(event) {
+  if (event && event.originalEvent instanceof Event) {
+    // show the upload label when we're responding to a click event
+    // (instead of being called from an error handler, which will
+    // display its own error label)
+    event.preventDefault();
```
Comment (miketaylr) [inline webcompat/static/js/lib/issue-wizard-bugform.js]: (honestly, i don't know why we're preventDefaulting here and not in the other bugform.js, -- I suspect it's not actually needed)

**Comment by miketaylr** [comment]
Thanks!
