### PR TITLE
Fixes #994. Better handle 413 errors when uploading an image.

### LINKED ISSUE #994: Handle 413 gracefully when reporting a bug
Right now if you try to upload a massive image, you get redirected to an ugly default NGINX 413 request entity too large page.

We need to instead of redirecting to that page, display a flash error and let the user select a smaller image.

#993 is related, but this bug is what happens in case that fails (maybe not possible, but we should cover both the front and back end experiences).

### PR DESCRIPTION
**Pull request by miketaylr**
This PR has 3 related changes:

1) Show a better flash message when the server returns a 413 (image too large)
2) Fix the z-index issue where the flash message was behind the image preview
3) Fix bugs in "image too large" validation that meant submit buttons were never re-enabled if you removed or changed the image.

r? @magsout

### CODE REVIEW

**Comment by miketaylr** [comment]
(Redirecting review to Adam, I think @magsout is swamped at work right now -- no issues ❤️ )

r? @adamopenweb

**Comment by miketaylr** [comment]
OK, now that #1018 is in will fix the merge conflicts.

**Comment by miketaylr** [comment]
Alright, rebased and fixed conflicts (and just manually tested again).

when travis is green, can you take a look @adamopenweb?

File: webcompat/static/js/lib/bugform.js [hunk 1]
```diff
@@ -284,7 +299,7 @@ function BugForm() {
   };
 
   this.addPreviewBackground = function(dataURI) {
-    if (!_.startsWith(dataURI, 'data:image/png;base64')) {
+    if (!_.startsWith(dataURI, 'data:image/')) {
```
Comment (miketaylr) [inline webcompat/static/js/lib/bugform.js]: This was a goofy bug that meant JPGs and GIFs, etc. wouldn't show image previews. 💩

File: webcompat/static/js/lib/bugform.js [hunk 2]
```diff
@@ -102,10 +102,14 @@ function BugForm() {
         this.loaderImage.hide();
         window.location.href = '/thanks/' + response.number;
       }, this),
-      error: function() {
+      error: _.bind(function(response) {
         var msg = 'There was an error trying to file the bug, try again?.';
-        wcEvents.trigger('flash:error', {message: msg, timeout: 4000});
-      }
+        if (response && response.status === 413) {
+          msg = 'The image is too big! Please choose something smaller than 4MB.';
```
Comment (miketaylr) [inline webcompat/static/js/lib/bugform.js]: In theory the user should never even be able to submit this, but better safe than sorry.

**Comment by magsout** [comment]
lgtm 👍 r+ ?

sorry for the daly ..

**Comment by magsout** [comment]
But you ask @adamopenweb so maybe let him do the review ?

**Comment by miketaylr** [comment]
No worries about the delay @magsout!

**Comment by miketaylr** [comment]
I'm gonna go ahead and merge, I think @adamopenweb was waiting on me to fix merge conflict junk before reviewing -- then I can do a deploy.
