### PR TITLE
Fixes #2171 - add test for 404 label search

### LINKED ISSUE #2171: Write functional tests for browser label search suggestion
The refactor broke this for a while, which exposed the fact we don't have tests for it:

https://github.com/webcompat/webcompat.com/pull/2168

STR and Expected behavior were more elegantly written by @softvision-oana-arbuzov in https://github.com/webcompat/webcompat.com/issues/2153#issue-298259452:

> **Steps to Reproduce:**
> 1. Navigate to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
> 2. Tap the "Search" field and type in a string that returns no results (e.g. Testtesttest).
> 3. After error message is displayed, observe suggestions - popular labels (e.g. android/chrome/firefox/ie).
> 4. Tap one of the popular labels and observe behavior (e.g. chrome).

> **Expected Behavior:**
> Redirect to specific page is performed
> (e.g. https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Abrowser-chrome).

### PR DESCRIPTION
**Pull request by zoepage**
@miketaylr I'm having issues with this test. Maybe you can help?

I've added a comment here: https://github.com/webcompat/webcompat.com/blob/issues/2171/tests/functional/search-auth.js#L230

The issue is that the 404 page is not loaded as the URL directs to `http://localhost:5000/api/issues?...` and not `http://localhost:5000/issues?...` as expected. So we don't have a redirect.

Please don't mind the URL params that are passed into the `openPage` function. Also the test itself contains a few things to try out.

### CODE REVIEW

File: tests/functional/_intern.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ intern.configure({
   reporters: [args.reporters ? args.reporters : "pretty"],
 
   functionalSuites: [
-    args.functionalSuites ? args.functionalSuites : "./tests/functional/*.js"
+    args.functionalSuites ? args.functionalSuites : "./tests/functional/search-auth.js"
```
Comment (miketaylr) [inline tests/functional/_intern.js]: (tip: when running a single test, you can do the following:

`node ./tests/functional/_intern.js functionalSuites=tests/functional/search-auth.js` 

And then it will only run that test)

Comment (miketaylr) [reply tests/functional/_intern.js]: Not useful to you now, but I'm going to fix some things in https://github.com/webcompat/webcompat.com/issues/2193 so you can just do `npm run:test:js -- --functionalSuites=blah --grep=interaction`, then you don't have to comment anything out either.

**Comment by miketaylr** [comment]
> The issue is that the 404 page is not loaded as the URL directs to http://localhost:5000/api/issues?... and not http://localhost:5000/issues?... as expected. So we don't have a redirect.

@zoepage can you explain in psuedo test code how you want to test this?

Also, where do you see that linked error message? 

When I try a search with no results, I get a 200 from `https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=asdfasdfasdfasdf+state:open+repo:webcompat/webcompat-tests&order=desc`, with a more or less empty response:

```
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```

thanks!

**Comment by miketaylr** [comment]
OK, I think I understand now.

```
Expected fixture file: /Users/mitaylor/dev/webcompat.com/tests/fixtures/api/issues.2c36ce8c0fec0c185101ba8f6b203f48.json
127.0.0.1 - - [27/Feb/2018 13:12:55] "GET /api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=noExpectedResult123 HTTP/1.1" 404 -

```

Since you're running in test mode against a new search URI (q=noExpectedREsults123), you'll need to add a new fixture file called `issues.2c36ce8c0fec0c185101ba8f6b203f48.json`, assuming you stick with that URI (the hash is computed against the params).

See https://github.com/webcompat/webcompat.com/blob/master/docs/tests.md#adding-fixtures

(the easiest way to create the fixture is do that search in non-testmode in Chrome, and copy and paste the response JSON into a new file with the expected name, and add a `"_fixture": true,` key to the first object)

File: tests/functional/_intern.js (hunk 1 above)
Comment (zoepage) [reply tests/functional/_intern.js]: 👍

**Comment by zoepage** [comment]
@miketaylr this looks like the missing piece. thanks! :)

File: tests/functional/search-auth.js [hunk 2]
```diff
@@ -198,6 +198,48 @@ registerSuite("Search (auth)", {
...
     },
 
+    "Label have correct URL after search without results"() {
+      // load up a garbage search, so we can more easily detect when
+      // the search values we want are loaded.
+      return FunctionalHelpers.openPage(
+        this,
+        url(
+          "/issues",
+          "?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc"
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: These are the default issues page params, right?

https://github.com/webcompat/webcompat.com/blob/61f4ef1be90d7d90eaec1af7a2fb75b1f055aeb9/webcompat/static/js/lib/models/issue.js#L123-L129

Probably not needed for `openPage` here if so.

File: tests/functional/search-auth.js [hunk 3]
```diff
@@ -198,6 +198,48 @@ registerSuite("Search (auth)", {
...
+        ),
+        ".grid"
+      )
+        .findByCssSelector("#js-SearchForm-input")
+        .clearValue()
+        .click()
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: I believe you don't need `clearValue()` here because by default the value will be empty on page load.

File: tests/functional/search-auth.js [hunk 4]
```diff
@@ -198,6 +198,48 @@ registerSuite("Search (auth)", {
...
+        .type("noExpectedResult123")
+        .submit()
+        .getProperty("value")
+        .then(function(text) {
+          assert.equal(
+            text,
+            "noExpectedResult123",
+            "The q param populated the search input."
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: This assertion description doesn't match what the test is doing -- it's not looking at `q`. But that said, what is the point of this part of the test? You're entering text into the input and making sure that it's still there? Is there a situation where it wouldn't be?

File: tests/functional/search-auth.js [hunk 5]
```diff
@@ -198,6 +198,48 @@ registerSuite("Search (auth)", {
...
+          );
+        })
+        .end()
+        .findByCssSelector("#x-search-bar")
+        .submit()
+        .end()
+        .sleep(2000)
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: Does this test work without the `sleep(2000)`? In theory, there's a default find timeout of 10 seconds.

File: tests/functional/search-auth.js [hunk 6]
```diff
@@ -198,6 +198,48 @@ registerSuite("Search (auth)", {
...
+        .findDisplayedByCssSelector(".label-browser-android")
+        .click()
+        .end()
+        .getCurrentUrl()
+        .then(function(url) {
+          assert.equal(
+            url,
+            "http://localhost:5000/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Abrowser-android",
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: I *think* it might be possible for this to fail if someone passed in a new `--siteRoot`, other than `http://localhost:5000/`. I'll follow a file up bug, because it's hardcoded in other tests.

Maybe a safer option here would be `assert(url.includes("q=label%3Abrowser-android"))`, since that's the interesting bit of the test.

File: tests/functional/search-auth.js (hunk 2 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: You're right. This is probably a left over of the hunt for the issue is had with the test before. Will remove.

File: tests/functional/search-auth.js (hunk 3 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: You're right. Leftover.

File: tests/functional/search-auth.js (hunk 4 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: I had issues with the input and got in some cases an `undefined`, but this is probably worth a separate test. Will file a follow up issue.

File: tests/functional/search-auth.js (hunk 6 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: 👍

Comment (zoepage) [reply tests/functional/search-auth.js]: I'll add this to this test, so we have less work later on.

File: tests/functional/search-auth.js (hunk 5 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: It does not as it looks like the test is loosing the scope through the redirect. The label element is not found.

File: tests/functional/search-auth.js (hunk 4 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: I can't reproduce right now. If it shows up again, I will add tests for that.

File: tests/functional/search-auth.js [hunk 7]
```diff
@@ -198,6 +198,34 @@ registerSuite("Search (auth)", {
...
+        this,
+        url(
+          "/issues"
+        ),
+        ".grid"
+      )
+        .findByCssSelector("#js-SearchForm-input")
+        .click()
+        .type("noExpectedResult123")
+        .submit()
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: I think we can get rid of this `submit()` too, since you're submitting the form just after.

File: tests/functional/search-auth.js (hunk 5 above)
Comment (miketaylr) [reply tests/functional/search-auth.js]: Weird, there isn't even a real redirect here, just some XHR requests. But if it works... seems good. :)

File: tests/functional/search-auth.js [hunk 8]
```diff
@@ -198,6 +198,34 @@ registerSuite("Search (auth)", {
...
+        .findByCssSelector("#x-search-bar")
+        .submit()
+        .end()
+        .sleep(2000)
+        .findDisplayedByCssSelector(".label-browser-android")
+        .click()
+        .end()
+        .getCurrentUrl()
+        .then(function(url) {
+          assert(url.includes("q=label%3Abrowser-android"));
```
Comment (miketaylr) [inline tests/functional/search-auth.js]: Can you add a description as a 2nd argument to `assert`?

Comment (miketaylr) [reply tests/functional/search-auth.js]: (oh weird, i already wrote this comment...) 👻

File: tests/functional/search-auth.js [hunk 9]
```diff
@@ -198,6 +198,34 @@ registerSuite("Search (auth)", {
         .end();
     },
 
+    "Label have correct URL after search without results"() {
+      // load up a garbage search, so we can more easily detect when
+      // the search values we want are loaded.
+      return FunctionalHelpers.openPage(
+        this,
```
[the remark this answers is not in the document]
Comment (zoepage) [reply tests/functional/search-auth.js]: This is a weird behaviour I ran into from time to time (UX wise). After fixing the lint issue, I forget to add the fixed file and push the commit without the fix. Maybe something like `npm run lint:js && git add .` would fix this?

File: tests/fixtures/api/issues.2c36ce8c0fec0c185101ba8f6b203f48.json [hunk 10]
```diff
@@ -0,0 +1,6 @@
+{
+	"_fixture": true,
```
[the remark this answers is not in the document]
Comment (zoepage) [reply tests/fixtures/api/issues.2c36ce8c0fec0c185101ba8f6b203f48.json]: 👍

File: tests/functional/search-auth.js (hunk 8 above)
Comment (zoepage) [reply tests/functional/search-auth.js]: fixed above.

File: tests/functional/search-auth.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (miketaylr) [reply tests/functional/search-auth.js]: Ah, interesting.

I finally just configured my text editor to auto-prettier all JS files on save, because I had done the same things as well. I'd be a little nervous about making `npm run lint:js && git add .` a default command, frequently I have a lot of unstaged changes that I want to include in different commits.
