### PR TITLE
Fixes #3417 - Add ability to navigate modal via left & right keys

### LINKED ISSUE #3417: [A11Y] Unable to navigate using right/left keys on “What is a web compatibility issue” popup
**Browser / Version**: Firefox Nightly 81.0a1 (2020-07-27) 
**Operating System**: Windows 10 Pro

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/issues/new
2. Using "Tab" key, navigate to the URL field and fill it in. 
3. Using "Tab" key, navigate to "Confirm" button.
4. Using "Tab" key, navigate to "Learn more about web compatibility" link.
5. Using "Enter" key, activate the popup.
6. Using "Right" key, try to navigate to the next slide.
7. Observe behavior.

**Expected Behavior:**
The next slide is displayed.

**Actual Behavior:**
Nothing happens, the next slide is not displayed.

**Notes:**
1. Screenshot attached.
2. According to "Inspector>Accessibility" tab, the navigation dots "must be focusable and should have interactive semantics".
image

image

Watchers:
@softvision-oana-arbuzov
@cipriansv

### PR DESCRIPTION
**Pull request by miketaylr**
r? @magsout 
r? @ksy36

### CODE REVIEW

File: webcompat/static/js/lib/issue-wizard-popup.js [hunk 1]
```diff
@@ -6,58 +6,71 @@ import $ from "jquery";
 import Mousetrap from "Mousetrap";
 import { sendAnalyticsEvent } from "./wizard/analytics.js";
 
-function Popup() {
-  this.init = function () {
+class Popup {
+  constructor() {
```
Comment (ksy36) [inline webcompat/static/js/lib/issue-wizard-popup.js:10]: es6 yay!

**Comment by miketaylr** [comment]
> looks good to me :)

thanks!
