### PR TITLE
Fixes #3378 - IE 11 fixes

### LINKED ISSUE #3378: webcompat form broken in IE11
**URL**: https://webcompat.com/issues/new

**Browser / Version**: IE 11.0
**Operating System**: Windows 10
**Tested Another Browser**: Yes Chrome

**Problem type**: Design is broken
**Description**: Items are overlapped
**Steps to Reproduce**:
The whole page is broken. Problem is quite obvious

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

### PR DESCRIPTION
**Pull request by ksy36**
This PR includes changes to make the site usable in IE 11 and also clean up of the old form js files

### CODE REVIEW

File: webcompat/static/js/lib/wizard/ui-utils.js [hunk 1]
```diff
@@ -17,11 +17,8 @@ export const scrollToElement = (element, delay = 250) => {
   setTimeout(() => {
     const topOfElement =
       window.pageYOffset + element.getBoundingClientRect().top - HEADER_HEIGHT;
-    window.scroll({ top: topOfElement, behavior: "smooth" });
+    $("html, body").animate({ scrollTop: topOfElement });
```
Comment (ksy36) [inline webcompat/static/js/lib/wizard/ui-utils.js:20]: Added it to make scrolling smooth in IE. So it makes it smooth in Safari as well :)

File: webcompat/static/js/lib/wizard/ui-utils.js [hunk 2]
```diff
@@ -17,11 +17,8 @@ export const scrollToElement = (element, delay = 250) => {
...
   }, delay);
-
-  //@todo figure out why this is needed
-  //this.isSubproblem ? 450 : 250
```
Comment (ksy36) [inline webcompat/static/js/lib/wizard/ui-utils.js:24]: I've accounted for this todo above, by putting showContainer in a callback of `show` function, that way we don't need a bigger timeout for animating the subcategory

File: webpack/webpack.prod.js [hunk 3]
```diff
@@ -15,8 +15,17 @@ const getOptions = (env) => {
...
 
   return {
+    sourceType: "unambiguous",
     babelrc: false,
-    presets: ["@babel/env"],
+    presets: [
+      [
+        "@babel/env",
+        {
+          corejs: "3",
```
Comment (ksy36) [inline webpack/webpack.prod.js:24]: I've noticed even though we have babel transpiling modern code, we still need polyfills for functions that do not supported in IE 11 (Array.includes, string.startsWith). I've used babel-polyfill in the past for polyfilling, but it's deprecated now in favor of core-js. With this config polyfills will be added automatically when a feature is unsupported in target environment (in this case target env is legacy browsers)

Explanation is here: https://stackoverflow.com/a/56505264

File: .babelrc [hunk 4]
```diff
@@ -1,4 +1,5 @@
 {
+  "sourceType": "unambiguous",
```
Comment (ksy36) [inline .babelrc:2]: Similarly to the legacy babel config, polyfills will be added here too, if needed (in case a certain feature is not supported in "modern" browsers)

Comment (miketaylr) [reply .babelrc:2]: (just linking myself to https://babeljs.io/docs/en/options#sourcetype `unambiguous` here)

File: webcompat/static/js/lib/wizard/ui-utils.js (hunk 2 above)
Comment (miketaylr) [reply webcompat/static/js/lib/wizard/ui-utils.js:24]: thanks, i was wondering what https://github.com/webcompat/webcompat.com/pull/3390/files#diff-1d0db961f9ba9046d10b32edb5d31394R16 was for.

File: webpack/webpack.common.js [hunk 5]
```diff
@@ -57,7 +37,10 @@ module.exports = {
     ],
   },
   resolve: {
-    modules: [path.resolve(__dirname, "../webcompat/static/js/vendor")],
+    modules: [
+      path.resolve(__dirname, "../webcompat/static/js/vendor"),
+      "node_modules",
```
Comment (miketaylr) [inline webpack/webpack.common.js:42]: This just means you can look inside `node_modules` for a module to include in the webpack bundle, correct?

File: webpack/webpack.prod.js (hunk 3 above)
Comment (miketaylr) [reply webpack/webpack.prod.js:24]: Thanks for the comment! Could you include a shorter version of this comment inside the JS file directly?

File: webcompat/static/js/lib/bugform-prefill.js [hunk 6]
```diff
@@ -1,52 +0,0 @@
-/* exported prefillForm */
```
Comment (miketaylr) [inline webcompat/static/js/lib/bugform-prefill.js:1]: Do you think you could split out all the old form deletion stuff into a separate commit? 

It's sort of a pain, but it would be nice to not have these 2 unrelated changes coupled together. If you want to crate an issue for that, it could be referenced in https://github.com/webcompat/webcompat.com/projects/12 as well.

File: webpack/webpack.common.js (hunk 5 above)
Comment (ksy36) [reply webpack/webpack.common.js:42]: yeah, so we could just import a package from node_modules, without specifying the full path.
it'll be just `import "package_name"`

File: webcompat/static/js/lib/bugform-prefill.js (hunk 6 above)
Comment (ksy36) [reply webcompat/static/js/lib/bugform-prefill.js]: Yeah, good point, I've moved them to the issue Karl created https://github.com/webcompat/webcompat.com/pull/3394

**Comment by ksy36** [comment]
ready for another look @miketaylr  :)

**Comment by ksy36** [comment]
Thanks!
