### PR TITLE
Fixes #2288: Refactor how we do form submission

### LINKED ISSUE #2288: Gracefully handle 415 errors on the client side
See https://github.com/webcompat/webcompat.com/issues/2276#issuecomment-375141425 and related discussion.

Basically, if/when an image is sent to upload.py and returns a 415, the bug report form should do something intelligent. At the very least, remove the problematic image and inform the user we don't like it.

### PR DESCRIPTION
**Pull request by miketaylr**
Just pushing these deps upgrades so I can see what tests fail and fix them. Not worth looking at yet!

### CODE REVIEW

**Comment by miketaylr** [comment]
homepage:
```
jQuery.Deferred exception: this.issues.fetch(...).success is not a function initialize@http://localhost:5000/js/lib/diagnose.js:19:5
e.View@http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:14728
n@http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:22929
@http://localhost:5000/js/lib/diagnose.js:39:3
l@http://localhost:5000/js/vendor/jquery-3.3.1.min.js:2:29373
a/</c<@http://localhost:5000/js/vendor/jquery-3.3.1.min.js:2:29677
 undefined
jquery-3.3.1.min.js:2:30920
TypeError: this.issues.fetch(...).success is not a function[Learn More]
```

**Comment by miketaylr** [comment]
```
Source map error: request failed with status 404
Resource URL: http://localhost:5000/js/vendor/backbone-1.3.3.min.js
Source Map URL: backbone-min.map[Learn More]
```

source map is here: https://github.com/jashkenas/backbone/blob/master/backbone-min.map

**Comment by miketaylr** [comment]
/issues

```
TypeError: this.issues.fetch(...).success is not a function[Learn More]
issue-list.js:359:7
fetchAndRenderIssues
http://localhost:5000/js/lib/issue-list.js:359:7
loadIssues
http://localhost:5000/js/lib/issue-list.js:338:9
initialize
http://localhost:5000/js/lib/issue-list.js:289:7
e.View
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:14728
n
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:22929
initSubViews
http://localhost:5000/js/lib/issue-list.js:591:22
initialize
http://localhost:5000/js/lib/issue-list.js:577:5
e.View
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:14728
n
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:22929
<anonymous>
http://localhost:5000/js/lib/issue-list.js:611:1
```

**Comment by miketaylr** [comment]
/issues/NNN

```
TypeError: this.issue.fetch(...).success is not a function[Learn More]
issues.js:384:7
fetchModels
http://localhost:5000/js/lib/issues.js:384:7
initialize
http://localhost:5000/js/lib/issues.js:325:7
e.View
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:14728
n
http://localhost:5000/js/vendor/backbone-1.3.3.min.js:8:22929
<anonymous>
http://localhost:5000/js/lib/issues.js:532:1
```

**Comment by miketaylr** [comment]
`TOTAL: tested 2 platforms, 160 passed, 2 failed` not bad after renaming some xhr success/error methods.

**Comment by miketaylr** [comment]
Interesting that the comments tests are being flaky.

**Comment by miketaylr** [comment]
TODO: 
- [ ] file a follow up issue to make any related changes to comment image uploads
- [ ] functional tests, maybe with some nice way to mock image and issue submission in test mode

**Comment by miketaylr** [comment]
lol
screen shot 2018-04-27 at 12 48 24 pm

**Comment by miketaylr** [comment]
OK! Tests are green. Annoying it took so much fiddling to get things to pass on Travis, while they pass locally.

Anyways,

this patch-set does the following things:

1. Upgrade jQuery and Backbone to latest versions
2. Refactor bugform.js image upload and form submission flow to be Deferred-based (jQuery's implementation of Promises)
3. Fixes the bugs where if the server sent back a 4XX error, you were stuck
4. Adds the notion of `@mockable_report` so we can mock out bug creation
5. Adds functional tests for bug creation, with and without screenshots

File: tests/functional/_intern.js [hunk 1]
```diff
@@ -42,7 +42,17 @@ const config = {
   tunnel: "selenium",
   tunnelOptions: {
     // this tells SeleniumTunnel to download geckodriver and chromedriver
-    drivers: ["firefox", { name: "chrome", version: "2.37" }]
+    drivers: ["firefox", { name: "chrome", version: "2.38" }]
+  },
+  capabilities: {
+    "moz:firefoxOptions": {
+      args: ["-headless"],
```
Comment (miketaylr) [inline tests/functional/_intern.js]: People might not like this... if they like to watch tests run in real time? Maybe I should remove it and add a commandline arg for it.

File: tests/functional/comments-auth.js [hunk 2]
```diff
@@ -88,15 +86,16 @@ registerSuite("Comments (auth)", {
...
         .type("tests/fixtures/green_square.png")
         .end()
-        .sleep(2000)
-        .findByCssSelector(".js-Comment-text")
-        .getProperty("value")
-        .then(function(val) {
+        .sleep(5000)
+        .execute(() => {
+          return document.querySelector("textarea").value;
+        })
```
Comment (Regaddi) [inline tests/functional/comments-auth.js]: Can be shortened to:

```
.execute(() => document.querySelector("textarea").value)
```

File: webcompat/static/js/lib/bugform.js [hunk 3]
```diff
@@ -500,40 +506,95 @@ function BugForm() {
...
+    // about which <button> was clicked (since one wasn't clicked).
+    // So we create a hidden <input> to pass along in the form data.
+    var hiddenEl = document.createElement("input");
+    hiddenEl.type = "hidden";
+    hiddenEl.name = "submit-type";
+    hiddenEl.value = this.clickedButton;
+    formEl.appendChild(hiddenEl);
+    formEl.submit();
+    dfd.resolve();
+    return dfd.promise();
```
Comment (Regaddi) [inline webcompat/static/js/lib/bugform.js]: Could we add the hidden input into the HTML of the form instead of generating it here and only update its value, when a submit button is clicked? It could contain the value `"anonymous"` initially.

File: tests/functional/_intern.js (hunk 1 above)
Comment (Regaddi) [reply tests/functional/_intern.js]: I personally prefer the headless version. But a cmd arg sounds reasonable.

File: webcompat/helpers.py [hunk 4]
```diff
@@ -407,6 +408,53 @@ def wrapped_func(*args, **kwargs):
...
+
+    This allows us to test form submission, always returning a special
+    issue 0 (that doesn't exist). It loads fixture data from a "zero.json"
+    template, and merges in the reported title and body, saving it to "0.json".
+
+    Note: unless you've created 0.json locally by running tests, navigating
+    there directly will 404. We don't check it into source control because
+    it can change depending on the test. But only tests should care abou this.
+    """
+    class Mocked201Response:
```
Comment (karlcow) [inline webcompat/helpers.py]: This creates a mocked response for functional tests when app.config['TESTING'].
I wonder what will be the outcome for unit-testing. I'm slightly uncomfortable. I have the feeling we are doing something wrong when our main code (outside of tests/) becomes peppered little by little by tests related things.

https://github.com/webcompat/webcompat.com/blob/fa99d5d35699911ed2cecad59e476f9f295feade/webcompat/helpers.py#L381-L407

https://github.com/webcompat/webcompat.com/blob/7517d8c1f25b9f70eca1536e240bd2f6ce69b95b/webcompat/views.py#L83-L87

https://github.com/webcompat/webcompat.com/blob/7517d8c1f25b9f70eca1536e240bd2f6ce69b95b/webcompat/views.py#L110-L111

The goal if I understand is to cut out the request to GitHub?

I don't have a solution right out of my hat :) 
but https://github.com/domenic/sinon-chai with http://sinonjs.org/
seems to be something to look at.

Comment (karlcow) [reply webcompat/helpers.py]: http://sinonjs.org/releases/v4.5.0/fake-xhr-and-server/

File: tests/functional/_intern.js (hunk 1 above)
Comment (miketaylr) [reply tests/functional/_intern.js]: @Regaddi maybe let's make headless the default and add a cmd arg for `--notHeadless` or something. It's only in weird debugging situations that I care to see it.

File: .gitignore [hunk 5]
```diff
@@ -26,6 +27,7 @@ webcompat/static/js/build/
 webcompat/static/js/dist/
 webcompat/**/*.min.css
 webcompat/static/css/dist/
+!webcompat/**/vendor/*.min.js
```
[the remark this answers is not in the document]
Comment (miketaylr) [reply .gitignore]: A few lines up (hard to see in this diff): `webcompat/**/*.min.js` means we ignore any updates to minified code. This change means git understands if we make an update to a minified file in the `vendor` directory, so if we update jQuery or something in the future. I can add a comment so it doesn't confuse me in 2 weeks. :)

File: webcompat/helpers.py [hunk 6]
```diff
@@ -407,6 +408,53 @@ def wrapped_func(*args, **kwargs):
     return wrapped_func
 
 
+def mockable_report(func):
+    """Mock out an API reponse for `issues.report_issue`, if in TESTING mode.
+
+    This allows us to test form submission, always returning a special
+    issue 0 (that doesn't exist). It loads fixture data from a "zero.json"
+    template, and merges in the reported title and body, saving it to "0.json".
```
[the remark this answers is not in the document]
Comment (miketaylr) [reply webcompat/helpers.py]: `/tmp/` seems better!

File: webcompat/helpers.py (hunk 4 above)
Comment (miketaylr) [reply webcompat/helpers.py]: > I have the feeling we are doing something wrong when our main code (outside of tests/) becomes peppered little by little by tests related things.

I think I agree with you that it's a code smell.

Comment (miketaylr) [reply webcompat/helpers.py]: Hm, so we could either land this now, and file a follow up bug to remove testing special-cased codepaths from everywhere. Let me investigate a bit first.

**Comment by miketaylr** [comment]
OK, I made the easy changes. Will look at sinonjs for xhr mocking now.

**Comment by miketaylr** [comment]
@karlcow I think we have 2 choices here: land as-is and file a follow up bug to find a better solution for serving fixture data from the server when in `TESTING` mode.

Or, remove the `@mockable_report` stuff (and the issue creation tests), and just land the refactored JS stuff. And then file a follow up bug to find a better solution for serving fixture data from the server when in `TESTING` mode. 😄 

I'm happy either way, I defer to what you think is better, thanks.

**Comment by miketaylr** [comment]
Um, except now all those tests are failing in Chrome. I think I'm just going to rip it out and file a follow up.

**Comment by miketaylr** [comment]
This `× firefox on linux 4.4.0-101-generic - Comments (auth) - Add a screenshot to a comment (5.67s)` test is making me sad. I'm going to remove it and see what can be added in `test_uploads.py`.

File: .gitignore (hunk 5 above)
[the remark this answers is not in the document]
Comment (karlcow) [reply .gitignore]: +1 to the comment. :)

**Comment by karlcow** [comment]
🤗 for all the code. And courage as we say in French.

**Comment by miketaylr** [comment]
> @miketaylr so I was a bit surprised by the check_rv_format(self, rv), but I guess you did it for the purpose of being DRY. Maybe it's not the right way to do it, but this is working.

Yeah, feel free to make it more pythonic next time you touch the file :P

I'll change the formatting issues then merge, thanks!
