### PR TITLE
Fixes #1574 - update regex and target field for text url removal

### LINKED ISSUE #1574: Photo link remains displayed in “Give more details” text area when removing the uploaded image
**Browser / Version:** Firefox 53.0.3 Release (Desktop), Chrome 58.0.3029.110 (Desktop), Firefox Nightly 55.0a1 (2017-05-31) (Mobile)
**Operating System:** Windows 10 Pro, Android 6.0.1

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Type in the required information and attach a screenshot.
4. After screenshot is attached, tap “Remove image upload” button. 
5. Observe behavior.

**Expected Behavior:**
Screenshot is removed and link no longer available in “Give more details” text area.

**Actual Behavior:**
Screenshot is removed, but link to the screenshot remains displayed in “Give more details” text area.

**Note:**
1. Submitting the issue, will display all uploaded photos, regardless they were previously removed.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

**Notes:**
1. Screenshot attached.

sv; 

screenshotlinknotremoved

### PR DESCRIPTION
**Pull request by cch5ng**
update existing test

cleanup: #1574; remove comments

tests: #1574; update existing selector

### CODE REVIEW

**Comment by cch5ng** [comment]
@karlcow R? it is JS but I think it was your code. also there was an existing test which appeared relevant.

File: webcompat/static/js/lib/bugform.js [hunk 1]
```diff
@@ -457,11 +457,8 @@ function BugForm() {
         // remove the last embedded image URL
         // Note: this could fail in weird ways depending on how
         // the user has edited the descField.
-        this.descField.val(function(idx, value) {
-          return value.replace(
-            /\[!\[[^\]]+\]\([^\)]+\)\]\([^\.]+.(?:bmp|gif|jpe*g*)\)$/,
-            ""
-          );
+        this.stepsToReproduceField.val(function(idx, value) {
+          return value.replace(/\[!\[[^\]]+\]\([^\)]+\)\]\([^\)]+\)$/);
```
Comment (karlcow) [inline webcompat/static/js/lib/bugform.js]: Apart of this. Testing in the Web Console of a browser with the correct syntax.

```js
> var image = "[![Screenshot Description](http://localhost:5000/uploads/2017/7/14afaf39-a749-4a55-8fc1-5b3bb7f040e7-thumb.jpg)](http://localhost:5000/uploads/2017/7/14afaf39-a749-4a55-8fc1-5b3bb7f040e7.jpg)" 
undefined 
> image.replace(/\[!\[[^\]]+\]\([^\)]+\)\]\([^\)]+\)$/, '') 
""
```

This is working.

**Comment by miketaylr** [comment]
Looks good, thanks @cch5ng!
